#!/bin/sh
alias \
	ls="exa -h --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"
	rmOrphans="pacman -Rns $(pacman -Qtdq)"
